name: payment images ci

on:
  push:
    paths:
      - 'microservices/payment/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/abc_msa_payment_management:latest .
          docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/abc_msa_payment_management:${{ steps.date.outputs.date }} .
          docker push ghcr.io/robert0714/abc_msa_payment_management:latest
          docker push ghcr.io/robert0714/abc_msa_payment_management:${{ steps.date.outputs.date }}